version: "3.8"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --api.insecure=true 
      - --providers.docker
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  fuseki:
    container_name: fuseki
    build: 
      context: ./triple-store
      dockerfile: store.Dockerfile
    # ports:
    #   - "3030:3030"
    volumes:
      - type: volume
        source: ttl-data
        target: /fuseki-base/databases
    environment:
      ADMIN_PASSWORD: ${PW}
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      QUERY_TIMEOUT: 600000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fuseki.rule=Host(`store.localhost`)"
      - "traefik.http.routers.fuseki.entrypoints=web"

  app:
    container_name: react-app
    build: 
      context: ./react-app
      dockerfile: app.Dockerfile
    # ports:
    #   - "1337:80"
    depends_on: 
      - fuseki
    links:
      - fuseki
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"

volumes:
  ttl-data:
