version: "3.8"

services:
  fuseki:
    container_name: fuseki
    build: 
      context: .
      dockerfile: store.Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - type: volume
        source: ttl-data
        target: /fuseki-base/databases
    environment:
      ADMIN_PASSWORD: ${PW}
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      QUERY_TIMEOUT: 600000
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3030/ds/sparql"]
        interval: 30s
        timeout: 10s
        retries: 5

  app:
    container_name: react-app
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "1337:80"
    depends_on: 
      - fuseki
    links:
      - fuseki
    restart: "always"



volumes:
  ttl-data:
