export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_DISCIPLINES_FAILED';

export const REQUEST_DISCIPLINE = 'REQUEST_DISCIPLINE';
export const REQUEST_LEVEL = 'REQUEST_LEVEL';
export const REQUEST_CONTEXT = 'REQUEST_CONTEXT';

export const CHANGE_ENDPOINTURL = 'CHANGE_ENDPOINTURL';

export const REQUEST_GRAPHS = 'REQUEST_GRAPHS';

export const CHANGE_ITEM_GRAPH = 'CHANGE_ITEM_GRAPH';

export const BUILD_SUB_GRAPH_PENDING = 'BUILD_SUB_GRAPH_PENDING';
export const BUILD_SUB_GRAPH_SUCCESS = 'BUILD_SUB_GRAPH_SUCCESS';
export const BUILD_SUB_GRAPH_FAILED = 'BUILD_SUB_GRAPH_FAILED';

export const CHANGE_COMPONENT_DATA = 'CHANGE_COMPONENT_DATA';
export const REMOVE_COMPONENT_DATA = 'REMOVE_COMPONENT_DATA';

export const ADD_DATA_COMPONENTS = 'ADD_DATA_COMPONENTS';
export const REMOVE_DATA_COMPONENT = 'REMOVE_DATA_COMPONENT';

export const CHANGE_GRAPH = "CHANGE_GRAPH";
